version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # H2 Database configurations
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./core/src/main/resources/db/data/demo
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      # JWT configurations
      - JWT_SECRET=testSecretKeytestSecretKeytestSecretKeytestSecretKey
      - JWT_EXPIRATION=86400000
    networks:
      - foundation-network

networks:
  foundation-network:
    driver: bridge