
DROP TABLE IF EXISTS GREET;

CREATE TABLE GREET
(
    ID            BIGINT PRIMARY KEY,
    CREATED_DATE  VARCHAR2(256),
    MODIFIED_DATE VARCHAR2(256),
    VERSION       BIGINT,
    IDENTIFIER    VARCHAR2(256),
    GREET_MESSAGE    VARCHAR(256)
);