server:
    port: 8081
    address: 0.0.0.0
springdoc:
    swagger-ui:
        use-root-path: true

app-info:
    title: "Broker Firm Challenge"
    version: "0.0.1"
    description: "Java Backend Developer Case"


author:
    fullName: 'Mustafa Arslan'
    email: 'mustafarslan35@gmail.com'

spring:
    application:
        name: core
    devtools:
        livereload:
            enabled: true
    profiles:
        active: "dev"
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    sql:
        init:
            mode: always
            platform: h2
            data-locations: classpath:./db/sql/h2/data-h2.sql
            schema-locations: classpath:./db/sql/h2/schema-h2.sql

    datasource:
        url: jdbc:h2:file:./core/src/main/resources/db/data/demo
        username: sa
        password: sa
        driverClassName: org.h2.Driver
    jpa:
        show-sql: true
        open-in-view: false
        defer-datasource-initialization: false
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
    data:
        redis:
            url: 0.0.0.0
            port: 6379
            password: ""
            ttl: 0
    kafka:
        bootstrap-servers: localhost:29092
    elasticsearch:
      url: localhost:9200

jwt:
    secret: testSecretKeytestSecretKeytestSecretKeytestSecretKey
    expiration: 86400000 # 24 hours in milliseconds