spring.application.name: core
springdoc:
    swagger-ui:
        use-root-path: true

author:
    fullName: 'Mustafa Arslan'
    email: 'mustafarslan35@gmail.com'

spring:
    profiles:
        active: "dev"
    h2:
        console.enabled: true
    datasource:
        url: jdbc:h2:file:./data/demo
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect